### ISSUE TITLE
Server ip too long problem

### ISSUE THREAD

**Issue by SLICER1153** [samarmeena/orbit#1]
![image](https://github.com/samarmeena/orbit/assets/115705551/10cb3091-8be1-4f49-b93a-aec1de32e784)

**Comment by SLICER1153** [comment]
when i try to add a server through its hostname and port, server ip is too long? is showing, but it should work.

**Comment by jindalpriyanshu101** [comment]
> when i try to add a server through its hostname and port, server ip is too long? is showing, but it should work.

Just insert the numeric IP instead of domain to resolve the error for now..

**Comment by vijayymmeena** [comment]
update to version 2
