### ISSUE TITLE
Sometimes Favourite servers appear twice.

### ISSUE THREAD

**Issue by SLICER1153** [samarmeena/orbit#2]
![image](https://github.com/samarmeena/orbit/assets/115705551/1d8cfa48-1d81-4ecc-9a46-e815038ca60c)

Issue described in title.

**Comment by SLICER1153** [comment]
see 
![image](https://github.com/samarmeena/orbit/assets/115705551/501065df-a1f3-4fc9-86be-7f5863ecbc68)

**Comment by SLICER1153** [comment]
![image](https://github.com/samarmeena/orbit/assets/115705551/ea7ec0b6-abf7-4bd0-952a-cf0040e9c1f8)

**Comment by vijayymmeena** [comment]
update to version 2
